spring:
  application:
    name: juggling-hive
  datasource:
    url: jdbc:hive2://10.28.200.210:21050/bbd_plutus_rating;auth=noSasl;t
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    generate-ddl: true
    show-sql: true
  profiles:
    active: oracle