server:
  port: 8088

spring:
  application:
    admin:
      enabled: false
    name: juggling-dynamicbeanload
  boot:
    admin:
      client:
        url: http://localhost:8080
        enabled: false
      ui:
        title: Juggling Dynamicbeanload
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.web.servlet.mvc: TRACE