CREATE TABLE "A_AUTH_USER" (	"ID" NUMBER(20,0) NOT NULL ENABLE,
   "TID" NUMBER(20,0),
   "EMPLOYEE_NO" NVARCHAR2(64),
   "NAME" NVARCHAR2(32),
   "PASSWORD" NVARCHAR2(128),
   "USERNAME" NVARCHAR2(64),
   "EMAIL" NVARCHAR2(64),
   "MOBILE" NVARCHAR2(32),
   "AVATAR" NVARCHAR2(255),
   "GMT_MODIFIED" DATE DEFAULT SYSDATE,
   "GMT_CREATE" DATE DEFAULT SYSDATE,
   "ACCOUNT_NON_EXPIRED" NUMBER(4,0) DEFAULT 1,
   "ACCOUNT_NON_LOCKED" NUMBER(4,0) DEFAULT 1,
   "CREDENTIALS_NON_EXPIRED" NUMBER(4,0) DEFAULT 1,
   "ENABLED" NUMBER(4,0) DEFAULT 1,
   "GROUP_ID" NUMBER(20,0),
   "DELETED" NUMBER(4,0) DEFAULT 0,
   "EXT_DATA" NVARCHAR2(2000),
    PRIMARY KEY ("ID")
);

CREATE OR REPLACE TRIGGER "USER_GMT_MODIFIED_UP_TRG" BEFORE UPDATE ON "A_AUTH_USER" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW
BEGIN
   :NEW.GMT_MODIFIED := SYSDATE;
END;